# Используем официальный образ Python в качестве базового
FROM python:3.12-slim

WORKDIR /app

# Копируем файл с зависимостями в контейнер
COPY requirements.txt .

# Устанавливаем зависимости
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь код приложения в контейнер
COPY . .

# Указываем команду для запуска бота
CMD ["python", "main.py"]
